[mgr]
cwd = { fg = "#cdcdcd", italic = true }

# Hovered
hovered = { bg = "#252530" }
preview_hovered = { bg = "#252530" }

# Find
find_keyword = { fg = "#141415", bg = "#f3be7c", bold = true }
find_position = { fg = "#6e94b2", bg = "#252530", bold = true }

# Marker
marker_copied = { fg = "#7fa563", bg = "#7fa563" }
marker_cut = { fg = "#d8647e", bg = "#d8647e" }
marker_marked = { fg = "#aeaed1", bg = "#aeaed1" }
marker_selected = { fg = "#141415", bg = "#f3be7c" }

# Tab
tab_active = { fg = "#cdcdcd", bg = "#252530" }
tab_inactive = { fg = "#606079", bg = "#141415" }
tab_width = 1

# Count
count_copied = { fg = "#cdcdcd", bg = "#606079" }
count_cut = { fg = "#cdcdcd", bg = "#d8647e" }
count_selected = { fg = "#cdcdcd", bg = "#606079" }

# Border
border_symbol = "â”‚"
border_style = { fg = "#252530" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

progress_label = { fg = "#cdcdcd", bold = true }
progress_normal = { fg = "#141415" }
progress_error = { fg = "#d8647e" }

# Permissions
permissions_t = { fg = "#6e94b2" }
permissions_r = { fg = "#f3be7c" }
permissions_w = { fg = "#d8647e" }
permissions_x = { fg = "#d8647e" }
permissions_s = { fg = "#606079" }

[mode]
normal_main = { fg = "#141415", bg = "#6e94b2", bold = true }
normal_alt = { fg = "#cdcdcd", bg = "#606079" }

select_main = { fg = "#141415", bg = "#aeaed1", bold = true }
select_alt = { fg = "#cdcdcd", bg = "#606079" }

unset_main = { fg = "#141415", bg = "#bb9dbd", bold = true }
unset_alt = { fg = "#cdcdcd", bg = "#606079" }

[select]
border = { fg = "#6e94b2" }
active = { fg = "#cdcdcd", bg = "#606079" }
inactive = { fg = "#cdcdcd" }

[input]
border = { fg = "#6e94b2" }
title = {}
value = { fg = "#aeaed1" }
selected = { bg = "#606079" }

[completion]
border = { fg = "#6e94b2" }
active = { fg = "#cdcdcd", bg = "#606079" }
inactive = { fg = "#cdcdcd" }

[tasks]
border = { fg = "#6e94b2" }
title = {}
hovered = { fg = "#cdcdcd", bg = "#606079" }

[which]
cols = 3
mask = { bg = "#141415" }
cand = { fg = "#6e94b2" }
rest = { fg = "#6e94b2" }
desc = { fg = "#aeaed1" }
separator = "  "
separator_style = { fg = "#606079" }

[notify]
title_info = { fg = "#6e94b2" }
title_warn = { fg = "#f3be7c" }
title_error = { fg = "#d8647e" }

[help]
on = { fg = "#d8647e" }
run = { fg = "#aeaed1" }
hovered = { bg = "#606079" }
footer = { fg = "#cdcdcd", bg = "#141415" }

[filetype]
rules = [
  # Media
  { mime = "{audio,video,image}/*", fg = "#aeaed1" },

  # Archives
  { mime = "application/*zip", fg = "#d8647e" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#d8647e" },

  # Documents
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#6e94b2" },

  # Special files
  { name = "*", is = "link", fg = "#d8647e" },
  { name = "*/", is = "link", fg = "#d8647e" },
  { name = "*", is = "orphan", bg = "#d8647e" },
  { name = "*", is = "exec", fg = "#d8647e" },

  # Fallback
  { name = "*/", fg = "#6e94b2" },
]

# vim:fileencoding=utf-8:foldmethod=marker
